// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbo9o05CsYMUlOs5V2G206UCPnQblk4NQ',
    appId: '1:864367406132:web:fd211d838d20f799d72e61',
    messagingSenderId: '864367406132',
    projectId: 'jelajahmy-ahmadnaufal',
    authDomain: 'jelajahmy-ahmadnaufal.firebaseapp.com',
    storageBucket: 'jelajahmy-ahmadnaufal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhZs1lPgMGjCjmvRh02a59jZY5m6G0Co0',
    appId: '1:864367406132:android:64827371a6c6f55ed72e61',
    messagingSenderId: '864367406132',
    projectId: 'jelajahmy-ahmadnaufal',
    storageBucket: 'jelajahmy-ahmadnaufal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_j6mJKKNv7Szbto0IQb_Na18Nv-B8s9w',
    appId: '1:864367406132:ios:9524d813c317bc8dd72e61',
    messagingSenderId: '864367406132',
    projectId: 'jelajahmy-ahmadnaufal',
    storageBucket: 'jelajahmy-ahmadnaufal.firebasestorage.app',
    iosBundleId: 'com.jelajahmy.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_j6mJKKNv7Szbto0IQb_Na18Nv-B8s9w',
    appId: '1:864367406132:ios:9524d813c317bc8dd72e61',
    messagingSenderId: '864367406132',
    projectId: 'jelajahmy-ahmadnaufal',
    storageBucket: 'jelajahmy-ahmadnaufal.firebasestorage.app',
    iosBundleId: 'com.jelajahmy.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbo9o05CsYMUlOs5V2G206UCPnQblk4NQ',
    appId: '1:864367406132:web:e8dc0b5eb05eaa69d72e61',
    messagingSenderId: '864367406132',
    projectId: 'jelajahmy-ahmadnaufal',
    authDomain: 'jelajahmy-ahmadnaufal.firebaseapp.com',
    storageBucket: 'jelajahmy-ahmadnaufal.firebasestorage.app',
  );
}
